// Code generated by MockGen. DO NOT EDIT.
// Source: password_reset_token.go
//
// Generated by this command:
//
//	mockgen -source=password_reset_token.go -destination=../../test/mocks/password_reset_token_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/akfaiz/go-starter-kit/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetTokenRepository is a mock of PasswordResetTokenRepository interface.
type MockPasswordResetTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockPasswordResetTokenRepositoryMockRecorder is the mock recorder for MockPasswordResetTokenRepository.
type MockPasswordResetTokenRepositoryMockRecorder struct {
	mock *MockPasswordResetTokenRepository
}

// NewMockPasswordResetTokenRepository creates a new mock instance.
func NewMockPasswordResetTokenRepository(ctrl *gomock.Controller) *MockPasswordResetTokenRepository {
	mock := &MockPasswordResetTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetTokenRepository) EXPECT() *MockPasswordResetTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasswordResetTokenRepository) Create(ctx context.Context, token *domain.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).Create), ctx, token)
}

// Delete mocks base method.
func (m *MockPasswordResetTokenRepository) Delete(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) Delete(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).Delete), ctx, userID)
}

// FindOne mocks base method.
func (m *MockPasswordResetTokenRepository) FindOne(ctx context.Context, userID int64) (*domain.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, userID)
	ret0, _ := ret[0].(*domain.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) FindOne(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).FindOne), ctx, userID)
}
