// Code generated by MockGen. DO NOT EDIT.
// Source: auth_guard.go
//
// Generated by this command:
//
//	mockgen -source=auth_guard.go -destination=../../test/mocks/security_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	security "github.com/akfaiz/go-starter-kit/internal/security"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthGuard is a mock of AuthGuard interface.
type MockAuthGuard struct {
	ctrl     *gomock.Controller
	recorder *MockAuthGuardMockRecorder
	isgomock struct{}
}

// MockAuthGuardMockRecorder is the mock recorder for MockAuthGuard.
type MockAuthGuardMockRecorder struct {
	mock *MockAuthGuard
}

// NewMockAuthGuard creates a new mock instance.
func NewMockAuthGuard(ctrl *gomock.Controller) *MockAuthGuard {
	mock := &MockAuthGuard{ctrl: ctrl}
	mock.recorder = &MockAuthGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthGuard) EXPECT() *MockAuthGuardMockRecorder {
	return m.recorder
}

// CheckLogin mocks base method.
func (m *MockAuthGuard) CheckLogin(ctx context.Context, ip, email string) (*security.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLogin", ctx, ip, email)
	ret0, _ := ret[0].(*security.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLogin indicates an expected call of CheckLogin.
func (mr *MockAuthGuardMockRecorder) CheckLogin(ctx, ip, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLogin", reflect.TypeOf((*MockAuthGuard)(nil).CheckLogin), ctx, ip, email)
}

// CheckRefresh mocks base method.
func (m *MockAuthGuard) CheckRefresh(ctx context.Context, ip string) (*security.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRefresh", ctx, ip)
	ret0, _ := ret[0].(*security.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRefresh indicates an expected call of CheckRefresh.
func (mr *MockAuthGuardMockRecorder) CheckRefresh(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRefresh", reflect.TypeOf((*MockAuthGuard)(nil).CheckRefresh), ctx, ip)
}

// OnLoginFailure mocks base method.
func (m *MockAuthGuard) OnLoginFailure(ctx context.Context, ip, email string) (*security.RateLimitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnLoginFailure", ctx, ip, email)
	ret0, _ := ret[0].(*security.RateLimitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OnLoginFailure indicates an expected call of OnLoginFailure.
func (mr *MockAuthGuardMockRecorder) OnLoginFailure(ctx, ip, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLoginFailure", reflect.TypeOf((*MockAuthGuard)(nil).OnLoginFailure), ctx, ip, email)
}

// OnLoginSuccess mocks base method.
func (m *MockAuthGuard) OnLoginSuccess(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnLoginSuccess", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnLoginSuccess indicates an expected call of OnLoginSuccess.
func (mr *MockAuthGuardMockRecorder) OnLoginSuccess(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLoginSuccess", reflect.TypeOf((*MockAuthGuard)(nil).OnLoginSuccess), ctx, email)
}
