openapi: 3.0.3
info:
  description: API starterkit with Echo v5, Gorm, Migris, and OTP auth reset flow
  title: Go Starter Kit API
  version: 1.0.0
servers:
- description: Local server
  url: http://localhost:8080
paths:
  /api/v1/auth/forgot-password/reset-password:
    post:
      description: Reset password with OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordWithOTPRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: Reset password with OTP
      tags:
      - Authentication
  /api/v1/auth/forgot-password/send-otp:
    post:
      description: Send forgot password OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendForgotPasswordOTPRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: Send forgot password OTP
      tags:
      - Authentication
  /api/v1/auth/forgot-password/verify-otp:
    post:
      description: Verify forgot password OTP
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyForgotPasswordOTPRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: Verify forgot password OTP
      tags:
      - Authentication
  /api/v1/auth/login:
    post:
      description: User Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTokenResponse'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: User Login
      tags:
      - Authentication
  /api/v1/auth/refresh-token:
    post:
      description: Refresh Token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTokenResponse'
          description: OK
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: Refresh Token
      tags:
      - Authentication
  /api/v1/auth/register:
    post:
      description: User Registration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTokenResponse'
          description: Created
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      summary: User Registration
      tags:
      - Authentication
  /api/v1/profile:
    delete:
      description: Delete profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      security:
      - bearerAuth: []
      summary: Delete profile
      tags:
      - Profile
    get:
      description: Get profile
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseProfileResponse'
          description: OK
      security:
      - bearerAuth: []
      summary: Get profile
      tags:
      - Profile
    put:
      description: Update profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseProfileResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      security:
      - bearerAuth: []
      summary: Update profile
      tags:
      - Profile
  /api/v1/profile/password:
    put:
      description: Update password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
          description: Unprocessable Entity
      security:
      - bearerAuth: []
      summary: Update password
      tags:
      - Profile
  /api/v1/users:
    get:
      description: List users
      parameters:
      - in: query
        name: page
        schema:
          type: integer
      - in: query
        name: limit
        schema:
          type: integer
      - in: query
        name: search
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
      - in: query
        name: order
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponseUserResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
      security:
      - bearerAuth: []
      summary: List users
      tags:
      - Users
  /api/v1/users/{id}:
    get:
      description: Get user by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUserResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Not Found
      security:
      - bearerAuth: []
      summary: Get user by ID
      tags:
      - Users
components:
  schemas:
    ChangePasswordRequest:
      properties:
        current_password:
          type: string
        new_password:
          type: string
        new_password_confirmation:
          type: string
      type: object
    ErrorResponse:
      properties:
        detail:
          example: Invalid request parameters
          type: string
        instance:
          example: request-id-12345
          type: string
        status:
          example: 400
          type: integer
        title:
          example: Bad Request
          type: string
        type:
          example: about:blank
          type: string
      type: object
    GenericResponse:
      properties:
        message:
          example: Operation successful
          type: string
        status:
          example: 200
          type: integer
      type: object
    LoginRequest:
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    PaginatedResponseUserResponse:
      properties:
        data:
          items:
            $ref: '#/components/schemas/UserResponse'
          type: array
        message:
          type: string
        pagination:
          $ref: '#/components/schemas/Pagination'
        status:
          type: integer
      type: object
    Pagination:
      properties:
        limit:
          type: integer
        page:
          type: integer
        total_data:
          format: int64
          type: integer
        total_pages:
          type: integer
      type: object
    ProfileResponse:
      properties:
        created_at:
          format: date-time
          type: string
        email:
          type: string
        email_verified_at:
          format: date-time
          nullable: true
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
    RefreshTokenRequest:
      properties:
        refresh_token:
          type: string
      type: object
    RegisterRequest:
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
      type: object
    ResetPasswordWithOTPRequest:
      properties:
        email:
          type: string
        otp:
          type: string
        password:
          type: string
        password_confirmation:
          type: string
      type: object
    ResponseProfileResponse:
      properties:
        data:
          $ref: '#/components/schemas/ProfileResponse'
        message:
          type: string
        status:
          example: 200
          type: integer
      type: object
    ResponseTokenResponse:
      properties:
        data:
          $ref: '#/components/schemas/TokenResponse'
        message:
          type: string
        status:
          example: 200
          type: integer
      type: object
    ResponseUserResponse:
      properties:
        data:
          $ref: '#/components/schemas/UserResponse'
        message:
          type: string
        status:
          example: 200
          type: integer
      type: object
    SendForgotPasswordOTPRequest:
      properties:
        email:
          type: string
      type: object
    TokenResponse:
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
      type: object
    UpdateProfileRequest:
      properties:
        email:
          type: string
        name:
          type: string
      type: object
    UserResponse:
      properties:
        created_at:
          format: date-time
          type: string
        email:
          type: string
        email_verified_at:
          format: date-time
          nullable: true
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
    ValidationErrorResponse:
      properties:
        detail:
          example: Invalid request parameters
          type: string
        errors:
          items:
            properties:
              field:
                example: email
                type: string
              message:
                example: Email is required
                type: string
            type: object
          type: array
        instance:
          example: request-id-12345
          type: string
        status:
          example: 422
          type: integer
        title:
          example: Bad Request
          type: string
        type:
          example: about:blank
          type: string
      type: object
    VerifyForgotPasswordOTPRequest:
      properties:
        email:
          type: string
        otp:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      scheme: Bearer
      type: http
